export type RevisaoCoopcerto = {
  status: string; motivos: string[]; detectada_em: string; importacao_id: string; hash_recebido: string;
  anterior: Record<string, string>; recebido: Record<string, string>;
};

export type VendaErp = {
  revisao_coopcerto?: RevisaoCoopcerto;
  agrupamento_parcelas?: Array<{id:string;parcelas:string;valor_bruto:string;valor_liquido?:string}>;
  id: string;
  importacao_id: string;
  numero_linha: number;
  data_venda?: string;
  data_venda_hora?: string;
  hora_venda?: string;
  terminal?: string;
  nsu?: string;
  valor_bruto?: string;
  valor_liquido?: string;
  forma_pagamento?: string;
  forma_pagamento_original?: string;
  bandeira?: string;
  bandeira_original?: string;
  tipo_produto?: string;
  tipo_produto_original?: string;
  parcelas?: string;
  cnpj_estabelecimento?: string;
  codigo_estabelecimento?: string;
  id_venda_erp?: string;
  status_venda?: string;
  status_venda_original?: string;
  duplicidade_status?: string;
  duplicidade_grupo?: string;
  conciliacao_id?: string;
  status_conciliacao?: string;
  score_conciliacao?: number;
  tipo_match?: string;
  hash_linha: string;
  valores_exibicao?: Record<string, unknown>;
};

export type VendaAdquirente = {
  revisao_coopcerto?: RevisaoCoopcerto;
  pix_vinculo_conflito?: string;
  pix_redundante?: string;
  id: string;
  importacao_id: string;
  adquirente: string;
  layout_origem: string;
  tipo_arquivo: string;
  codigo_registro: string;
  numero_linha: number;
  data_venda?: string;
  data_venda_hora?: string;
  hora_venda?: string;
  data_pagamento?: string;
  valor_bruto?: string;
  valor_liquido?: string;
  valor_taxa?: string;
  percentual_taxa?: string;
  nsu?: string;
  codigo_autorizacao?: string;
  terminal?: string;
  codigo_estabelecimento?: string;
  bandeira?: string;
  modalidade?: string;
  parcelas?: string;
  status_transacao?: string;
  codigo_produto?: string;
  duplicidade_status?: string;
  duplicidade_grupo?: string;
  conciliacao_id?: string;
  status_conciliacao?: string;
  score_conciliacao?: number;
  tipo_match?: string;
  valores_exibicao?: Record<string, unknown>;
};
