import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const rootDir = path.resolve(__dirname, '../../..');
export const storageDir = path.join(rootDir, 'storage');
export const importacoesDir = path.join(storageDir, 'importacoes');
export const entradaDir = path.join(importacoesDir, 'entrada');
export const processandoDir = path.join(importacoesDir, 'processando');
export const processadosDir = path.join(importacoesDir, 'processados');
export const erroDir = path.join(importacoesDir, 'erro');
export const desconhecidosDir = path.join(importacoesDir, 'desconhecidos');
export const dbDir = path.join(storageDir, 'db');
export const importacoesJsonPath = path.join(dbDir, 'importacoes.json');
export const vendasErpJsonPath = path.join(dbDir, 'vendas-erp.json');
export const vendasInterdataJsonPath = path.join(dbDir, 'vendas-interdata.json');
export const vendasAdquirentesJsonPath = path.join(dbDir, 'vendas-adquirentes.json');
export const sicoobLayoutPspPixJsonPath = path.join(dbDir, 'sicoob-layout-psp-pix.json');
export const sipagLayout20SPixJsonPath = path.join(dbDir, 'sipag-layout-2-0-s-pix.json');
export const sipagLayout20SCartoesJsonPath = path.join(dbDir, 'sipag-layout-2-0-s-cartoes.json');
export const sipagLayout20PJsonPath = path.join(dbDir, 'sipag-layout-2-0-p.json');
export const sipagLayout20RJsonPath = path.join(dbDir, 'sipag-layout-2-0-r.json');
export const sipagFiserv76SPixJsonPath = path.join(dbDir, 'sipag-fiserv-layout-7-6-s-pix.json');
export const sipagFiserv76SCartoesJsonPath = path.join(dbDir, 'sipag-fiserv-layout-7-6-s-cartoes.json');
export const sipagFiserv76PJsonPath = path.join(dbDir, 'sipag-fiserv-layout-7-6-p.json');
export const cieloLayout1515Cielo03JsonPath = path.join(dbDir, 'cielo-layout-15-15-cielo03.json');
export const cieloLayout1515Cielo16JsonPath = path.join(dbDir, 'cielo-layout-15-15-cielo16.json');
export const cieloLayout1515Cielo04JsonPath = path.join(dbDir, 'cielo-layout-15-15-cielo04.json');
export const sicrediFiserv74SPixJsonPath = path.join(dbDir, 'sicredi-fiserv-layout-7-4-s-pix.json');
export const sicrediFiserv74SCartoesJsonPath = path.join(dbDir, 'sicredi-fiserv-layout-7-4-s-cartoes.json');
export const sicrediFiserv74PJsonPath = path.join(dbDir, 'sicredi-fiserv-layout-7-4-p.json');
export const sicrediFiserv74RJsonPath = path.join(dbDir, 'sicredi-fiserv-layout-7-4-r.json');
export const convcard203CvJsonPath = path.join(dbDir, 'convcard-layout-2-0-3-cv.json');
export const convcard203CpJsonPath = path.join(dbDir, 'convcard-layout-2-0-3-cp.json');
export const convcard203CcJsonPath = path.join(dbDir, 'convcard-layout-2-0-3-cc.json');
export const convcard203TbJsonPath = path.join(dbDir, 'convcard-layout-2-0-3-tb.json');
export const convcard203ControleJsonPath = path.join(dbDir, 'convcard-layout-2-0-3-controle.json');
export const conciliacoesJsonPath = path.join(dbDir, 'conciliacoes.json');
export const conversoesJsonPath = path.join(dbDir, 'conversoes.json');
export const logsDir = path.join(storageDir, 'logs');
export const remoteEdiDir = path.join(storageDir, 'remote-edi');
export const keysDir = path.join(storageDir, 'keys');
