import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const rootDir = path.resolve(__dirname, '../../..');
export const storageDir = process.env.STORAGE_DIR ? path.resolve(process.env.STORAGE_DIR) : path.join(rootDir, 'storage');
export const importacoesDir = path.join(storageDir, 'importacoes');
export const entradaDir = path.join(importacoesDir, 'entrada');
export const processandoDir = path.join(importacoesDir, 'processando');
export const processadosDir = path.join(importacoesDir, 'processados');
export const erroDir = path.join(importacoesDir, 'erro');
export const desconhecidosDir = path.join(importacoesDir, 'desconhecidos');

// Referências lógicas das tabelas PostgreSQL. Não representam arquivos locais.
export const importacoesTabela = 'importacoes';
export const vendasErpTabela = 'vendas_erp';
export const vendasInterdataTabela = 'vendas_interdata';
export const vendasAdquirentesTabela = 'vendas_adquirentes';
export const sicoobLayoutPspPixTabela = 'sicoob_layout_psp_pix';
export const sipagLayout20SPixTabela = 'sipag_layout_2_0_s_pix';
export const sipagLayout20SCartoesTabela = 'sipag_layout_2_0_s_cartoes';
export const sipagLayout20PTabela = 'sipag_layout_2_0_p';
export const sipagLayout20RTabela = 'sipag_layout_2_0_r';
export const sipagFiserv76SPixTabela = 'sipag_fiserv_layout_7_6_s_pix';
export const sipagFiserv76SCartoesTabela = 'sipag_fiserv_layout_7_6_s_cartoes';
export const sipagFiserv76PTabela = 'sipag_fiserv_layout_7_6_p';
export const cieloLayout1515Cielo03Tabela = 'cielo_layout_15_15_cielo03';
export const cieloLayout1515Cielo16Tabela = 'cielo_layout_15_15_cielo16';
export const cieloLayout1515Cielo04Tabela = 'cielo_layout_15_15_cielo04';
export const sicrediFiserv74SPixTabela = 'sicredi_fiserv_layout_7_4_s_pix';
export const sicrediFiserv74SCartoesTabela = 'sicredi_fiserv_layout_7_4_s_cartoes';
export const sicrediFiserv74PTabela = 'sicredi_fiserv_layout_7_4_p';
export const sicrediFiserv74RTabela = 'sicredi_fiserv_layout_7_4_r';
export const convcard203CvTabela = 'convcard_layout_2_0_3_cv';
export const convcard203CpTabela = 'convcard_layout_2_0_3_cp';
export const convcard203CcTabela = 'convcard_layout_2_0_3_cc';
export const convcard203TbTabela = 'convcard_layout_2_0_3_tb';
export const convcard203ControleTabela = 'convcard_layout_2_0_3_controle';
export const vrLayout16apTabela = 'vr_layout_16ap';
export const pluxeeLayoutTabela = 'pluxee_layout';
export const aleloLayoutTabela = 'alelo_layout';
export const aleloPagamentosTabela = 'alelo_pagamentos';
export const ticketCeAdm40VendasTabela = 'ticket_ceadm40_vendas';
export const ticketCeAdm40PagamentosTabela = 'ticket_ceadm40_pagamentos';
export const sipagVendasPixCsvTabela = 'sipag_vendas_pix_csv';
export const sipagExtratoTransacoesAutorizadasTabela = 'sipag_extrato_transacoes_autorizadas';
export const sipagExtratoVendasPixTabela = 'sipag_extrato_vendas_pix';
export const sipagExtratoVendasAReceberTabela = 'sipag_extrato_vendas_a_receber';
export const sipagExtratoVendasRecebidasTabela = 'sipag_extrato_vendas_recebidas';
export const coopcertoCabalVendasCsvTabela = 'coopcerto_cabal_vendas_csv';
export const coopcertoExtratoVendasAReceberTabela = 'coopcerto_extrato_vendas_a_receber';
export const coopcertoExtratoVendasRecebidasTabela = 'coopcerto_extrato_vendas_recebidas';
export const conciliacoesTabela = 'conciliacoes';
export const conversoesTabela = 'conversoes';
export const logsDir = path.join(storageDir, 'logs');
export const remoteEdiDir = path.join(storageDir, 'remote-edi');
export const keysDir = path.join(storageDir, 'keys');
