import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ChevronLeft, ChevronRight, CopyCheck, RefreshCw, Search, ShieldCheck } from 'lucide-react';
import { API_URL, apiFetch } from '../lib/api';
import { formatarMoedaBrasil } from '../lib/formatters';

type GrupoDuplicidade={grupo:string;tabela:string;chave:string;criterio:string;quantidade:number;registros:Array<Record<string,unknown>>};
type ResultadoDuplicidades={sucesso:boolean;aplicado:boolean;atualizado_em:string;resumo:{grupos_total:number;vendas_adquirentes:number;vendas_interdata:number;registros_adquirentes_em_grupos:number;registros_interdata_em_grupos:number;atualizados_adquirentes:number;atualizados_interdata:number};grupos:GrupoDuplicidade[]};
const POR_PAGINA=20;

export function DuplicidadesPage(){
 const[resultado,setResultado]=useState<ResultadoDuplicidades|null>(null);const[loading,setLoading]=useState(false);const[message,setMessage]=useState('');const[tipo,setTipo]=useState<'TODOS'|'ADQUIRENTE'|'ERP'>('TODOS');const[busca,setBusca]=useState('');const[pagina,setPagina]=useState(1);const[expandido,setExpandido]=useState<string|null>(null);
 async function carregarDuplicidades(aplicar=false){setLoading(true);setMessage('');try{const response=await apiFetch(`${API_URL}/api/duplicidades/verificar${aplicar?'?aplicar=true':''}`,{method:aplicar?'POST':'GET',headers:{'Content-Type':'application/json'}});const data=await response.json();if(!response.ok)throw new Error(data?.mensagem||'Erro ao verificar duplicidades.');setResultado(data);setMessage(aplicar?'Verificação concluída e marcações aplicadas.':'Verificação concluída sem alterar dados.');}catch(error){setMessage(error instanceof Error?error.message:'Erro ao verificar duplicidades.');}finally{setLoading(false)}}
 async function removerDuplicidades(manter:'mais_antigo'|'mais_recente'){const confirmado=window.confirm(`ATENÇÃO: esta ação remove registros do banco. Remover duplicados mantendo o ${manter==='mais_antigo'?'registro mais antigo':'registro mais recente'} de cada grupo?`);if(!confirmado)return;setLoading(true);setMessage('');try{const response=await apiFetch(`${API_URL}/api/duplicidades/remover`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tabela:'ambas',manter})});const data=await response.json();if(!response.ok)throw new Error(data?.mensagem||'Erro ao remover duplicidades.');const removidos=Number(data?.vendas_adquirentes?.removidos||0)+Number(data?.vendas_interdata?.removidos||0);setMessage(`Limpeza concluída. ${removidos} registro(s) duplicado(s) removido(s).`);await carregarDuplicidades(false);}catch(error){setMessage(error instanceof Error?error.message:'Erro ao remover duplicidades.');}finally{setLoading(false)}}
 useEffect(()=>{void carregarDuplicidades(false)},[]);useEffect(()=>setPagina(1),[tipo,busca]);
 const grupos=resultado?.grupos||[],resumo=resultado?.resumo;
 const filtrados=useMemo(()=>grupos.filter(g=>{const erp=g.tabela.includes('interdata')||g.tabela.includes('erp');if(tipo==='ERP'&&!erp)return false;if(tipo==='ADQUIRENTE'&&erp)return false;const q=busca.trim().toLowerCase();return !q||`${g.grupo} ${g.tabela} ${g.criterio} ${g.chave}`.toLowerCase().includes(q)||g.registros.some(r=>JSON.stringify(r).toLowerCase().includes(q));}),[grupos,tipo,busca]);
 const paginas=Math.max(1,Math.ceil(filtrados.length/POR_PAGINA)),visiveis=filtrados.slice((pagina-1)*POR_PAGINA,pagina*POR_PAGINA);
 const registro=(r:Record<string,unknown>,index:number)=><div className={`duplicate-record-card ${index===0?'base':'candidate'}`}><div className="duplicate-record-title"><strong>{index===0?'Registro principal':'Possível duplicado'}</strong><span>{index===0?'Referência do grupo':'Revisar correspondência'}</span></div><div className="duplicate-record-grid"><span><small>Data / hora</small>{String(r.data_venda||'-')} {String(r.hora_venda||'')}</span><span><small>Valor</small>{formatarMoedaBrasil(r.valor_bruto)}</span><span><small>NSU</small>{String(r.nsu||'-')}</span><span><small>Autorização</small>{String(r.codigo_autorizacao||'-')}</span><span><small>Terminal</small>{String(r.terminal||'-')}</span><span><small>Status</small>{String(r.duplicidade_status||'-')}</span></div></div>;
 return <section className="duplicates-page"><div className="duplicates-heading"><div><h1>Controle de Duplicidades</h1><p className="muted">Revise possíveis registros repetidos antes de qualquer alteração no banco.</p></div><div className="duplicates-safe-badge"><ShieldCheck size={17}/>Verificação segura</div></div>
 <div className="duplicate-primary-actions"><button className="button primary" onClick={()=>carregarDuplicidades(false)} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/>{loading?'Verificando...':'Verificar duplicidades'}</button><button className="button secondary" onClick={()=>carregarDuplicidades(true)} disabled={loading}><CopyCheck size={16}/>Marcar duplicidades prováveis</button>{resultado?.atualizado_em&&<span className="duplicate-last-check">Última verificação: {new Date(resultado.atualizado_em).toLocaleString('pt-BR')}</span>}</div>
 {message&&<div className="notice">{message}</div>}
 <div className="cards duplicate-summary"><div className="card"><span>Grupos encontrados</span><strong>{resumo?.grupos_total??0}</strong></div><div className="card"><span>Adquirentes</span><strong>{resumo?.vendas_adquirentes??0}</strong></div><div className="card"><span>ERP INTERDATA</span><strong>{resumo?.vendas_interdata??0}</strong></div><div className="card warning"><span>Registros envolvidos</span><strong>{(resumo?.registros_adquirentes_em_grupos??0)+(resumo?.registros_interdata_em_grupos??0)}</strong></div></div>
 <div className="panel duplicate-review-panel"><div className="duplicate-review-header"><div><h2>Grupos para revisão</h2><span>{filtrados.length.toLocaleString('pt-BR')} grupo(s) conforme os filtros</span></div><div className="duplicate-filters"><div className="duplicate-tabs"><button className={tipo==='TODOS'?'active':''} onClick={()=>setTipo('TODOS')}>Todos</button><button className={tipo==='ADQUIRENTE'?'active':''} onClick={()=>setTipo('ADQUIRENTE')}>Adquirentes</button><button className={tipo==='ERP'?'active':''} onClick={()=>setTipo('ERP')}>ERP</button></div><label className="duplicate-search"><Search size={15}/><input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar grupo, NSU, autorização..."/></label></div></div>
 {visiveis.length===0?<div className="duplicate-empty"><CopyCheck size={30}/><strong>Nenhuma duplicidade provável encontrada</strong><span>Os critérios e filtros atuais não retornaram grupos para revisão.</span></div>:<div className="duplicate-groups">{visiveis.map(g=>{const key=`${g.tabela}-${g.grupo}`,aberto=expandido===key;return <article className="duplicate-group" key={key}><button className="duplicate-group-head" onClick={()=>setExpandido(aberto?null:key)}><div><strong>{g.grupo}</strong><span className={`duplicate-origin ${g.tabela.includes('interdata')?'erp':'adq'}`}>{g.tabela.includes('interdata')?'ERP':'ADQUIRENTE'}</span></div><div className="duplicate-group-meta"><span>{g.quantidade} registros</span><span title={g.criterio}>{g.criterio}</span><ChevronRight size={17} className={aberto?'expanded':''}/></div></button>{aberto&&<div className="duplicate-group-body"><div className="duplicate-comparison">{g.registros.map((r,i)=><React.Fragment key={`${key}-${i}`}>{registro(r,i)}</React.Fragment>)}</div></div>}</article>})}</div>}
 <div className="duplicate-pagination"><button disabled={pagina<=1} onClick={()=>setPagina(p=>p-1)}><ChevronLeft size={15}/></button><span>Página {pagina} de {paginas}</span><button disabled={pagina>=paginas} onClick={()=>setPagina(p=>p+1)}><ChevronRight size={15}/></button></div></div>
 <details className="duplicate-danger-zone"><summary><AlertTriangle size={17}/>Ações avançadas de remoção</summary><div><p>Estas ações removem registros do banco. Revise os grupos antes de utilizá-las.</p><div className="action-row"><button className="button secondary" onClick={()=>removerDuplicidades('mais_antigo')} disabled={loading||grupos.length===0}>Remover mantendo mais antigo</button><button className="button secondary" onClick={()=>removerDuplicidades('mais_recente')} disabled={loading||grupos.length===0}>Remover mantendo mais recente</button></div></div></details>
 </section>;
}
